import React from 'react';
import './Guide.css';
import img2Image from '../../assets/image44.png';
import windImage from '../../assets/windImage.gif';
import img3Image from '../../assets/image.png';
import img4Image from '../../assets/Rectangle12.png';
import img58Image from '../../assets/image 58.png';

const guides = [
  {
    title: "What are Renewable Energy Certificates (RECs)?",
    description: "Renewable Energy Certificates (RECs) are tradable assets generated by renewable energy sources, for example, Solar Panel System and Wind Turbines.\nYou will be able to register one REC when 1 megawatt-hour (MWh) of electricity is produced.\nSo why are they valuable? In short, Companies around the world buy RECs as a form of carbon credit in order to offset their carbon emissions and meet their sustainability targets.",
    date: "July 20th 2024",
    image: img2Image,
    link: "#"
  },
  {
    title: "How are RECs Regulated?",
    description: "RECs are required to be tracked to ensure they are valid and are only sold once. RECs require to be certified by authorized registries.",
    date: "July 20th 2024",
    image: windImage,
    link: "#"
  },
  {
    title: "The Process of Trading RECs",
    description: "RECs are required to be tracked in order to ensure they are valid and are only sold once. RECs require to be certified by authorized registries.",
    date: "July 20th 2024",
    image: img4Image,
    link: "#"
  },
  {
    title: "Registering Your Asset",
    description: "RECs are required to be tracked in order to ensure they are valid and are only sold once. RECs require to be certified by authorized registries.",
    date: "July 20th 2024",
    image: img3Image,
    link: "#"
  },
  {
    title: "Monetary Value of RECs",
    description: "Renewable Energy Certificates (RECs) are tradable assets generated by renewable energy sources for example Solar Panel System and Wind Turbines. You will be able to register one REC when 1 megawatt-hour (MWh) of electricity is produced. \n So why are they valuable? In short, Companies around the world buy RECs as a form of carbon credit in order to offset their carbon emissions and meet their sustainability targets.",
    date: "July 20th 2024",
    image: img58Image,
    link: "#"
  }
];

const Guide = () => {
  return (
    <div className="guide-library">
      <h1><svg xmlns="http://www.w3.org/2000/svg" width="140" height="4" viewBox="0 0 140 4" fill="none">
        <path d="M0 2H140" stroke="#222831" strokeWidth="3" />
      </svg>GUIDE LIBRARY<svg xmlns="http://www.w3.org/2000/svg" width="140" height="4" viewBox="0 0 140 4" fill="none">
          <path d="M0 2H140" stroke="#222831" strokeWidth="3" />
        </svg></h1>
      <div className="horizontal-card">
        <div className="guide-content">
          <h2>{guides[0].title}</h2>
          {/* Replace \n with <br /> for line breaks */}
          <p>{guides[0].description.split('\n').map((text, index) => (
            <React.Fragment key={index}>
              {text}
              <br />
            </React.Fragment>
          ))}</p>
          <div>
            <p className="guide-date">{guides[0].date}</p>
            <a href={guides[0].link} className="guide-link">Read more</a>
          </div>
        </div>
        <img src={guides[0].image} alt={guides[0].title} className="guide-image" />
      </div>
      <div className="guide-list">
        {guides.slice(1, 4).map((guide, index) => (
          <div className="guide-item" key={index}>
            <img src={guide.image} alt={guide.title} className="guide-image" />
            <div className="guide-content">
              <h2>{guide.title}</h2>
              <p>{guide.description.split('\n').map((text, idx) => (
                <React.Fragment key={idx}>
                  {text}
                  <br />
                </React.Fragment>
              ))}</p>
              <div>
                <p className="guide-date">{guide.date}</p>
                <a href={guide.link} className="guide-link">Read more</a>
              </div>
            </div>
          </div>
        ))}
      </div>
      <div className="horizontal-card horizontal2">
        <img src={guides[4].image} alt={guides[4].title} className="guide-image" />
        <div className="guide-content">
          <h2>{guides[4].title}</h2>
          <p>{guides[4].description.split('\n').map((text, index) => (
            <React.Fragment key={index}>
              {text}
              <br />
            </React.Fragment>
          ))}</p>
          <div>
            <p className="guide-date">{guides[4].date}</p>
            <a href={guides[4].link} className="guide-link">Read more</a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Guide;
